{
  "services": {
    "shell": {
      "entrypoint": [
        "/bin/bash"
      ],
      "image": "ghcr.io/williamjacksn/ansible",
      "init": true,
      "volumes": [
        "./:/app"
      ]
    }
  }
}