services:
  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/ansible
    init: true
    volumes:
      - ./:/home/python/docker-ansible
    working_dir: /home/python/docker-ansible
